### ISSUE TITLE
Add user interaction element lifecycle

### ISSUE THREAD

**Issue by mandryllo** [tailor-cms/tce-template#9]
# Proposition

For the purpose of the CEK - CDA backend interface, we propose adding a new user interaction element lifecycle. This proposed lifecycle would consist of two server hooks (let's discuss the naming of everything):
- `afterUserInteraction` hook (interface on the bottom)
	- used when the user interacts with CEK element in some way 
	- user for processing of payload from the CEK frontend and provides element state, submission, and events to the CDA backend
- `beforeDisplay` hook (interface on the bottom)
	- used when the CEK element is rendered (displayed to the user), either on initial render or on re-render after a user interacts with the CEK element (and after calling the `afterUserInteraction` hook)
	- used for formatting of display state to the user

## CDA Backend

The initial idea of the CDA backend around all of this can be found [here](https://miro.com/app/board/uXjVMsCSL-Q=/?moveToWidget=3458764564303334418&cot=14) (something may differ as this was the initial discovery around it).

### Persisting of data

CDA backend will have two tables in which the CEK element will/can persist data:
- submission
	- every intentional user submission inside the CEK element (e.g. answering a question)
- element state
	- implicit i.e. only the CEK is aware of it (e.g. latest user timestamp on a video)
	- always one per context
	- consists of:
		- `isCompleted` flag
			- required, used by the CDA backend to calculate user progress and for section locking/unlocking
		- `serverState` 
			- can be anything CEK element needs to persist to the database for the next interaction/display
			- not returned to the CEK frontend, needs to be formatted in the `beforeDisplay` hook 

```typescript

type ContentElementServerState = any;

interface ContentElementState {
  serverState?: ContentElementServerState;
  isCompleted: boolean;
}
```

### CDA context

Will consist of the CDA specific context (e.g. `userId`, `courseRunId`)

```typescript
interface Context {
  userId: string;
  cohortId: string;
  courseRunId: string;
  waveId: string; // not sure we need this one, this is also not a generic name for CEK to support
  elementId: number;
}
```

## Flow

The full flow should look like this (focus only on CDA - CEK interfacing)

1. CEK frontend (Display component) sends a request to the CDA backend after some user interaction
	- The CDA backend will not validate or process the payload of the request, it will validate just if the authenticated user has access to this piece of content (CEK element inside some course run)
2. CDA backend calls CEK element `afterUserInteraction` hook 
	- CDA backend provides payload (sent from the CEK frontend), CDA-specific context, element state & element data
	-  CEK element returns submission, element state, and events
3. CDA backend stores submission & state in its database, events (CDA backend will validate xAPI format) are sent to analytics
4. CDA backend calls CEK element `beforeUserDisplay` hook
	- CDA backend provides last submission and element state
	- CEK element returns formatted display state which will be returned to the CEK frontend
5. CDA backend returns to CEK frontend only the formatted display state (Of course, when the CEK element gets rendered the the flow starts on step 5)

```typescript
type ContentElementPayload = any;
type ContentElementSubmission = any;
type ContentElementEvent = any;
type ContentElementDisplayState = any;
type ContentElementData = any;

interface AfterUserInteractionHookOutput {
  elementState: ContentElementState;
  submission?: ContentElementSubmission; 
  events?: ContentElementEvent[];

interface CEKElement {
  afterUserInteractionHook(
    payload: ContentElementPayload, // sent from CEK frontend, will be processed in this hook
    context: Context, 
    elementState: ContentElementState,
	elementData: ContentElementData // authored element data
  ): AfterUserInteractionHookOutput;
  beforeDisplayHook(
    elementState: ContentElementState,
    lastSubmission: ContentElementSubmission // in the case when the user is interacting with the element this is submission returned from afterUserInteraction hook
  ): ContentElementDisplayState;
}
```

Open questions:
- Can this interface be extended (and in which way) to support aggregation & input-output functionality in the future (This proposition does not include those, let's discuss that in a separate issue)?
- Should `beforeDisplayHook` also get `context`?
- Should `elementState` & `lastSubmission` be part of the `context`?

**Comment by dbettini** [comment]
> Should elementState & lastSubmission be part of the context?

I'd say everything CDA specific should be. This would in the future allow us just to extend it without changing CEK. CEK interface would then be:
```
interface ContentElementRuntime {
  afterInteractionHook(payload: any, elementData: any, context: any): any;
  beforeDisplayHook(elementData: any, context: any): any;
}
```
And we would be able to implement context in any way we want on CDA and in our CEK elements.

> Should beforeDisplayHook also get context?

The most flexible way would be injecting the same context into both hooks (excluding the payload, of course). It's also the easiest for us on CDA, since we could use the same context generating function. Also, if we go with my previous recommendation where submissions and state are a part of context as well, then this is done by default. So I would say doing everything through context has multiple benefits - no further changes to CEK runtime interfaces, and flexibility to decide what we send to these hooks on CDA. If we don't go with this approach, we would have to change function signatures, while this way we can just expand the context interface.

> Can this interface be extended (and in which way) to support aggregation & input-output functionality in the future (This proposition does not include those, let's discuss that in a separate issue)?

If we pass everything CDA specific through context, it should be pretty straightforward. That means this interface:
```
interface Context {
  userId: string;
  cohortId: string;
  courseRunId: string;
  waveId: string; // not sure we need this one, this is also not a generic name for CEK to support
  elementId: number;
  submissions: ContentElementSubmission[],
  state: ContentElementState,
  // ... anything else
}
```
As you can see, I also added submissions as an array. This is for future proofing if there are any elements that would require reading all instead of just their last submission. We could still just send only the latest submission initially, making it an array of 1 element only. This would avoid us changing the context interface on existing elements and CDA if that happens (replacing lastSubmission with submissions). But going with that approach is fine by me as well.

**Comment by underscope** [comment]
Hi @dbettini,

I definitely agree this is the most generic thing to do, and if it works for the team let's do it. 

I have to note that this approach has some implications/limitations in terms of:
- not having mechanism to tackle concepts like submissions (within CEK you would rely only on seed and you would need to construct it; you wouldn't be able to get previous submission / simulate multiple submissions if we are not implementing mechanism for handling specific properties)
- similar for state
- everyone would need to make sure to implement context mock and maintain it over time

@dbettini @mandryllo @tueda-hvd Let me know if this is an acceptable tradeoff for your needs.

**Comment by tueda-hvd** [comment]
Hi @underscope - a couple of questions about those tradeoffs:

> not having mechanism to tackle concepts like submissions (within CEK you would rely only on seed and you would need to construct it; you wouldn't be able to get previous submission / simulate multiple submissions if we are not implementing mechanism for handling specific properties)

What kinds of mechanisms are you thinking of here? What kind of support specifically does the `any` type prevent us from providing? I'm just not clear on what the tradeoff is here.

> everyone would need to make sure to implement context mock and maintain it over time

Is this going to be a concern when we get to e.g. aggregation and social service integration? That could be a lot of context to manually provide for testing purposes. Are there other ways we could provide standardized support for data generation (e.g. via fakerjs or something similar)?

**Comment by tueda-hvd** [comment]
@underscope thank you, I think I understand. Yes, that sounds fine for now. Perhaps once the interface has hardened a bit we can more strongly type those parameters and build the additional features, but what's proposed here should be fine for now.

**Comment by dbettini** [comment]
> everyone would need to make sure to implement context mock and maintain it over time

@underscope  I'm guessing those would be needed anyway to correctly write tests for these elements, since they will use some context outside of submissions (e.g. authorId to generate xApi events etc.)

> not having mechanism to tackle concepts like submissions (within CEK you would rely only on seed and you would need to construct it; you wouldn't be able to get previous submission / simulate multiple submissions if we are not implementing mechanism for handling specific properties)

Would it be possible to create another, CEK specific hook that handles the output and uses some kind of storage? That could solve that problem and allow both a good authoring UX while still giving CDA all the benefits. Example:
```js
// context is seeded on startup into some kind of in-memory storage

onUserInteractionHook(payload, context): OnInteractionOutput {
  return { submission: payload.data, events: [{ actor: context.authorId, ... } };
}

afterUserInteractionHook(onInteractionOutput, context): NewContext {
  context.submissions.push(onInteractionOutput.submission); // If we go with an array
  context.lastSubmission = submission;
  // ... update the context in any way
  return context;
}

// CEK calls:

const output = onUserInteractionHook(payload, storage.context);
storage.context = afterUserInteractionHook(output, storage.context);
```
This means afterUserInteractionHook would be renamed to onUserInteractionHook - but another naming is possible as well. We could just call it `updateContext/refreshContext`. The point of this is that the new hook would be called by CEK, but we wouldn't use it on CDA - it would allow authors to use a storage that would allow getting the previous submission (or all submissions that occured - it's on the author to decide). This means that the seeded context would just be a starting point, while this function would allow continuous state transformations. 

This sounds similar to what you had in mind in the first place @underscope, the difference being it wouldn't be a part of CEK, but the author would have to implement it. The reason I like this approach more than providing the storage service directly to the initial interaction hook is because the CDA has less optimization options then (query by element vs entire page/course run).

> Is this going to be a concern when we get to e.g. aggregation and social service integration?

@tueda-hvd my suggestion above should give more flexibility for this as well

**Comment by underscope** [comment]
If we are not leaning towards having a standardised context and mechanisms it provides we can pretty much do anything we want, the only thing is that all of it needs to be taken care of by the element developer (as you suggested). Let's touch base in person today and finalize the proposal 😉
